import type { NextPage } from 'next'
import {useState} from "react"
import Head from 'next/head'
import { useRouter } from "next/router";
import {useEffect} from "react"
import Axios from 'axios'
import CampaignMenu from '../../components/CampaignMenu';
import CampaignDetailCards from '../../components/CampaignDetailCards';
import BarChart from '../../components/BarChart';



const Campaign: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;
  const [campaign, setCampaign] = useState(null);

  
  

  useEffect(() => {
    async function getCampaign() {
      const data = await Axios.post(`/api/campaigns/get`, {
        campaign_name: id
      });
      console.log(data.data);
      setCampaign(data.data);
    }
    getCampaign();
  }, []);

  return (
    <div className='p-8 max-w-7xl mx-auto' style={{minHeight: "100vh"}}>
      <Head>
        <title>Ember | SSGM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CampaignMenu campaign={campaign}/>
      <div className='flex justify-between w-full'>
        <CampaignDetailCards campaign={campaign} />
        <div className='flex flex-col w-2/3 ml-12 space-y-12 justify-between mt-8'>
          <BarChart idName="chart1" />
        </div>
      </div>
    </div>
  )
}

export default Campaign