import type { NextPage } from 'next'
import { useState } from "react"
import Head from 'next/head'
import { useRouter } from "next/router";
import { useEffect } from "react"
import Axios from 'axios'
import CampaignMenu from '../../components/campaign/CampaignMenu';
import DirectorAgeChart from '../../components/charts/DirectorAgeChart';
import CompanyLocationChart from '../../components/charts/CompanyLocationChart';
import CampaignCostChart from "../../components/charts/CampaignCostChart"


const Campaign: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;
  const [campaign, setCampaign] = useState(null);
  const [activeFilter, setActiveFilter] = useState("COMPANY_LOCATION")

  useEffect(() => {
    async function getCampaign() {
      const data = await Axios.post(`/api/campaigns/get`, {
        campaign_name: id
      });

      setCampaign(data.data);
    }
    getCampaign();
  }, []);

  return (
    <div className='p-4 max-w-7xl mx-auto' style={{ minHeight: "100vh" }}>
      <Head>
        <title>Ember | SSGM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CampaignMenu setCampaign={setCampaign} campaign={campaign} />
      <div className="flex py-3" style={{ borderBottom: "2px solid rgba(243, 244, 246, 1)" }}>
        <p onClick={() => setActiveFilter("COMPANY_LOCATION")} className={`${activeFilter === "COMPANY_LOCATION" ? "text-red-400" : "text-gray-400"} relative cursor-pointer w-40 flex justify-center`}>
          Company Location
          {activeFilter === "COMPANY_LOCATION" && <div className="absolute top-9 h-1 w-full bg-red-400" style={{}} />}
        </p>
        <p onClick={() => setActiveFilter("DIRECTOR_AGE")} className={`${activeFilter === "DIRECTOR_AGE" ? "text-red-400" : "text-gray-400"} relative cursor-pointer w-40 flex justify-center`}>
          Director Age
          {activeFilter === "DIRECTOR_AGE" && <div className="absolute top-9 h-1 w-full bg-red-400" style={{}} />}
        </p>
        <p onClick={() => setActiveFilter("CAMPAIGN_COST")} className={`${activeFilter === "CAMPAIGN_COST" ? "text-red-400" : "text-gray-400"} relative cursor-pointer w-40 flex justify-center`}>
          Campaign Cost
          {activeFilter === "CAMPAIGN_COST" && <div className="absolute top-9 h-1 w-full bg-red-400" style={{}} />}
        </p>
      </div>
      <div className='flex flex-col justify-between mt-4 w-full'>
        {activeFilter === "COMPANY_LOCATION" && <>
          {/* @ts-ignore*/}
          <CompanyLocationChart idName="chart2" campaign={campaign?.id} />
        </>}
        {activeFilter === "DIRECTOR_AGE" && <>
          {/* @ts-ignore*/}
          <DirectorAgeChart idName="chart1" campaign={campaign?.id} />
        </>}
        {activeFilter === "CAMPAIGN_COST" && <>
          {/* @ts-ignore*/}
          <CampaignCostChart idName="chart3" campaign={campaign?.id} />
        </>}
      </div>
    </div >
  )
}

export default Campaign