import type { NextPage } from 'next'
import Head from 'next/head'
import CreateCampaignForm from '../../components/CreateCampaignForm'


const Campaigns: NextPage = () => {

  return (
    <div className='px-12 py-4 max-w-5xl mx-auto' style={{minHeight: "100vh"}}>
      <Head>
        <title>Ember | SSGM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div className='my-8'>
       <h1 className='text-3xl'>Create Campaign</h1>
     </div>
     <CreateCampaignForm />
    </div>
  )
}

export default Campaigns