import type { NextPage } from 'next'
import Head from 'next/head'

import {useEffect, useState} from "react"
import Axios from 'axios'
import CampaignsMenu from '../../components/CampaignsMenu'
import CampaignsList from '../../components/CampaignsList'

const Campaigns: NextPage = () => {

  const [campaigns, setCampaigns] = useState([])
  const [filter, setFilter] = useState("")

  const getData = async () => {
    const { data } = await Axios.get(`api/campaigns/all`);
    console.log(data);
    setCampaigns(data)
  }

  useEffect( () => {
    getData();
  })

  return (
    <div style={{minHeight: "100vh"}}>
      <Head>
        <title>Ember | SSGM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <CampaignsMenu filter={filter} setFilter={setFilter} />
     <CampaignsList filter={filter} campaigns={campaigns}/>
    </div>
  )
}

export default Campaigns