import type { NextPage } from 'next'
import Head from 'next/head'

import {useEffect, useState} from "react"
import Axios from 'axios'
import CampaignsList from '../../components/CampaignsList'

const Campaigns: NextPage = () => {

  const [campaigns, setCampaigns] = useState([])
  const [filter, setFilter] = useState("")

  const getData = async () => {
    const { data } = await Axios.get(`api/campaigns/all`);
    
    setCampaigns(data)
  }

  useEffect( () => {
    getData();
  })

  return (
    <div className='px-12 py-4 mx-auto' style={{minHeight: "100vh"}}>
      <Head>
        <title>Ember | SSGM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div className='my-8'>
       <h1 className='text-4xl'>Campaigns</h1>
     </div>
     <div className='mb-8 max-w-6xl text-gray-600'>
       <p>In assessing the key leveraging technology, one should think outside the box. On the other hand, any the bottom line can fully utilize the flexible manufacturing system. One must therefore dedicate resources to the marginalised empirical management option immediately.. In the light of a unique facet of the discipline of resource planning, it is clear that an unambiguous concept of the cohesive legitimisation makes little difference to the secondary complex flexibility. Therefore a maximum of flexibility is required.</p>
     </div>
     <CampaignsList filter={filter} setFilter={setFilter} campaigns={campaigns}/>
    </div>
  )
}

export default Campaigns