import type { NextPage } from 'next'
import Head from 'next/head'
import Modal from 'react-modal';
import {useEffect, useState} from "react"
import Axios from 'axios'
import CampaignCostChart from '../components/CampaignCostChart';

const Home: NextPage = () => {

  const [modalIsOpen, setIsOpen] = useState(false);

  function openModal() {
    setIsOpen(true);
  }

  function afterOpenModal() {
    // references are now sync'd and can be accessed.
    console.log("hi")
  }

  function closeModal() {
    setIsOpen(false);
  }

  return (
    <div className='max-w-7xl mx-auto relative' style={{minHeight: "100vh"}}>
      <Head>
        <title>Ember | SSGM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal
        isOpen={modalIsOpen}
        onAfterOpen={afterOpenModal}
        onRequestClose={closeModal}
        style={{maxWidth: 800, maxHeight: "70vh", zIndex: 9999}}
        contentLabel="Example Modal"
        shouldCloseOnOverlayClick
      >
        <div className='mt-12'>
        <CampaignCostChart idName="chart3" campaign={1} />
        </div>
      </Modal>

      <h1 className='text-5xl font-light m-auto pt-16 pb-4 text-center'><span className='font-medium text-red-400'>SSGM</span> Statistics -</h1>
      <h1 className='text-5xl m-auto pb-16 font-light text-center'>Turning Data into Ideas</h1>

      <div className='flex justify-between'>
        <div className='w-1/4 flex flex-col'>
          <div style={{height: 1}} className='w-full bg-gray-600' />
          <h1 className='py-2'>Companies</h1>
          <p className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>1</span> <span>Most popular SIC Codes</span></p>
          <p className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>2</span> <span>SIC popularity Timeline</span></p>
          <p className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>3</span> <span>Ember Grade System Breakdown</span></p>
          <p className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>4</span> <span>Company Formation Occurence Rate</span></p>
        </div>
        <div className='w-1/4 flex flex-col'>
          <div style={{height: 1}} className='w-full bg-gray-600' />
          <h1 className='py-2'>Ember</h1>
          <p className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>1</span> <span>Most popular SIC Codes (Active Users)</span></p>
        </div>
        <div className='w-1/4 flex flex-col'>
          <div style={{height: 1}} className='w-full bg-gray-600' />
          <h1 className='py-2'>Campaigns</h1>
          <p onClick={openModal} className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>1</span> <span>Cost Comparison Treemap</span></p>
          <p className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>2</span> <span>Widest Reaching</span></p>
          <p className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>3</span> <span>Highest Costing</span></p>
          <p className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>4</span> <span>Top Performing</span></p>
        </div>
      </div>
      <div className='flex justify-around my-12'>
      <div className='w-1/4 flex flex-col'>
          <div style={{height: 1}} className='w-full bg-gray-600' />
          <h1 className='py-2'>Directors</h1>
          <p className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>1</span> <span>Average Age of A/B Grade Directors</span></p>
          <p className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>2</span> <span>Directors with Multiple Companies</span></p>
          <p className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>3</span> <span>Top Locations</span></p>
        </div>
        <div className='w-1/4 flex flex-col'>
          <div style={{height: 1}} className='w-full bg-gray-600' />
          <h1 className='py-2'>Memes</h1>
          <p className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>1</span> <span>Most Common Name</span></p>
          <p className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>2</span> <span>SSGM Search Performance</span></p>
        </div>
      </div>
    </div>
  )
}

export default Home