import type { NextPage } from 'next'
import Head from 'next/head'
import Modal from 'react-modal';
import { useEffect, useState } from "react"
import CampaignCostChart from '../components/CampaignCostChart';
import MostPoppingSICCodes from '../components/MostPoppingSICCodes';
import SicPopularityTimeline from "../components/SicPopularityTimeline"
import EmberGradeBreakdown from '../components/EmberGradeBreakdown';
import CompanyFormationBreakdown from '../components/CompanyFormationBreakdown';
import EmberSICBreakdown from '../components/EmberSICBreakdown';
import CampaignSizeBreakdown from '../components/CampaignSizeBreakdown';
import CampaignCostBreakdown from '../components/CampaignCostBreakdown';
import TopPerformingCampaigns from '../components/TopPerformingCampaigns';
import AverageDirectorAge from '../components/AverageDirectorAge';
import DirectorOwnedCompanyCount from '../components/DirectorOwnedCompanyCount';
import TopDirectorLocation from '../components/TopDirectorLocation';
import MostPopularName from '../components/MostPopularName';
import SSGMPerformanceChart from '../components/SSGMPerformanceChart';
import CloseIcon from '@mui/icons-material/Close';

const StatisticMap = {
  ["COST_COMPARISON"]: <CampaignCostChart idName="chart" campaign={1} />,
  ["MOST_POPPING_SIC_CODES"]: <MostPoppingSICCodes />,
  ["SIC_TIMELANE_CHART"]: <SicPopularityTimeline />,
  ["EMBER_GRADE_BREAKDOWN"]: <EmberGradeBreakdown />,
  ["COMPANY_FORMATION_BREAKDOWN"]: <CompanyFormationBreakdown />,
  ["EMBER_SIC_BREAKDOWN"]: <EmberSICBreakdown />,
  ["CAMPAIGN_SIZE_BREAKDOWN"]: <CampaignSizeBreakdown />,
  ["CAMPAIGN_COST_BREAKDOWN"]: <CampaignCostBreakdown />,
  ["TOP_PERFORMING_CAMPAIGNS"]: <TopPerformingCampaigns />,
  ["AVERAGE_DIRECTOR_AGE"]: <AverageDirectorAge />,
  ["DIRECTOR_OWNED_COMPANY_COUNT"]: <DirectorOwnedCompanyCount />,
  ["TOP_DIRECTOR_LOCATION"]: <TopDirectorLocation />,
  ["MOST_POPULAR_NAME"]: <MostPopularName />,
  ["SSGM_PERFORMANCE_CHART"]: <SSGMPerformanceChart />
}

const getCurrentStatisticComponent = (currentStatistic: any) => {
  return StatisticMap[currentStatistic]
}

const Home: NextPage = () => {

  const [modalIsOpen, setIsOpen] = useState(false);
  const [currentStatistic, setCurrentStatistic]: any = useState(null)


  useEffect(() => {
    if (currentStatistic) {
      setIsOpen(true)
    }
  }, [currentStatistic])

  function afterOpenModal() {
    // references are now sync'd and can be accessed.
    console.log("hi")
  }

  function closeModal() {
    setIsOpen(false);
    setCurrentStatistic(null)
  }

  return (
    <div className='max-w-7xl mx-auto relative' style={{ minHeight: "100vh" }}>
      <Head>
        <title>Ember | SSGM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal
        isOpen={modalIsOpen}
        onAfterOpen={afterOpenModal}
        onRequestClose={closeModal}
        onClose={closeModal}
        style={{ maxWidth: 800, maxHeight: "70vh", zIndex: 9999 }}
        contentLabel="Example Modal"
        shouldCloseOnOverlayClick
      >
        <div style={{ height: "90%" }} className='mt-12 relative'>
          {getCurrentStatisticComponent(currentStatistic)}
          <div style={{ left: 17, bottom: 60 }} onClick={closeModal} className='absolute cursor-pointer'><CloseIcon /></div>
        </div>
      </Modal>

      <h1 className='text-5xl font-light m-auto pt-16 pb-4 text-center'><span className='font-medium text-red-400'>SSGM</span> Statistics -</h1>
      <h1 className='text-5xl m-auto pb-16 font-light text-center'>Turning Data into Ideas</h1>

      <div className='flex justify-between'>
        <div className='w-1/4 flex flex-col'>
          <div style={{ height: 1 }} className='w-full bg-gray-600' />
          <h1 className='py-2'>Companies</h1>
          <p onClick={() => setCurrentStatistic("MOST_POPPING_SIC_CODES")} className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>1</span> <span>Most popular SIC Codes</span></p>
          <p onClick={() => setCurrentStatistic("SIC_TIMELANE_CHART")} className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>2</span> <span>SIC popularity Timeline</span></p>
          <p onClick={() => setCurrentStatistic("EMBER_GRADE_BREAKDOWN")} className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>3</span> <span>Ember Grade System Breakdown</span></p>
          <p onClick={() => setCurrentStatistic("COMPANY_FORMATION_BREAKDOWN")} className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>4</span> <span>Company Formation Occurence Rate</span></p>
        </div>
        <div className='w-1/4 flex flex-col'>
          <div style={{ height: 1 }} className='w-full bg-gray-600' />
          <h1 className='py-2'>Ember</h1>
          <p onClick={() => setCurrentStatistic("EMBER_SIC_BREAKDOWN")} className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>1</span> <span>Most popular SIC Codes (Active Users)</span></p>
        </div>
        <div className='w-1/4 flex flex-col'>
          <div style={{ height: 1 }} className='w-full bg-gray-600' />
          <h1 className='py-2'>Campaigns</h1>
          <p onClick={() => setCurrentStatistic("COST_COMPARISON")} className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>1</span> <span>Cost Comparison Treemap</span></p>
          <p onClick={() => setCurrentStatistic("CAMPAIGN_SIZE_BREAKDOWN")} className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>2</span> <span>Widest Reaching</span></p>
          <p onClick={() => setCurrentStatistic("CAMPAIGN_COST_BREAKDOWN")} className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>3</span> <span>Highest Costing</span></p>
          <p onClick={() => setCurrentStatistic("TOP_PERFORMING_CAMPAIGNS")} className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>4</span> <span>Top Performing</span></p>
        </div>
      </div>
      <div className='flex justify-around my-12'>
        <div className='w-1/4 flex flex-col'>
          <div style={{ height: 1 }} className='w-full bg-gray-600' />
          <h1 className='py-2'>Directors</h1>
          <p onClick={() => setCurrentStatistic("AVERAGE_DIRECTOR_AGE")} className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>1</span> <span>Average Age of A/B Grade Directors</span></p>
          <p onClick={() => setCurrentStatistic("DIRECTOR_OWNED_COMPANY_COUNT")} className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>2</span> <span>Directors with Multiple Companies</span></p>
          <p onClick={() => setCurrentStatistic("TOP_DIRECTOR_LOCATION")} className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>3</span> <span>Top Locations</span></p>
        </div>
        <div className='w-1/4 flex flex-col'>
          <div style={{ height: 1 }} className='w-full bg-gray-600' />
          <h1 className='py-2'>Memes</h1>
          <p onClick={() => setCurrentStatistic("MOST_POPULAR_NAME")} className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>1</span> <span>Most Common Name</span></p>
          <p onClick={() => setCurrentStatistic("SSGM_PERFORMANCE_CHART")} className='py-3 flex text-xl font-light hover:text-red-400 cursor-pointer'><span className='font-normal pr-6'>2</span> <span>SSGM Search Performance</span></p>
        </div>
      </div>
    </div>
  )
}

export default Home